### ISSUE TITLE
Symfony 6.3 upgrade - Session was used while the request was declared stateless.

### ISSUE THREAD

**Issue by ChristianVermeulen** [lexik/LexikJWTAuthenticationBundle#1143]
I'm trying to upgrade to Symfony 6.3 and getting the following error all of a sudden:

`Session was used while the request was declared stateless.`

LexikJWTAuthenticationBundle: v2.19.0
PHP: v8.2

### Full stacktrace
```
Symfony\Component\HttpKernel\Exception\UnexpectedSessionUsageException:
Session was used while the request was declared stateless.

  at vendor/symfony/http-kernel/EventListener/AbstractSessionListener.php:213
  at Symfony\Component\HttpKernel\EventListener\AbstractSessionListener->onKernelResponse(object(ResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:220)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.response', object(ResponseEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ResponseEvent), 'kernel.response')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:139)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ResponseEvent), 'kernel.response')
     (vendor/symfony/http-kernel/HttpKernel.php:199)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse(object(JWTAuthenticationSuccessResponse), object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:145)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/application/vendor/autoload_runtime.php')
     (public/index.php:5)        
```

**Comment by mbabker** [comment]
There isn't anything in this bundle that directly uses the session, though.  The stack trace in this case isn't the most helpful thing because that's just the exception being thrown by the framework when checking if the session was used, it's not telling you what started the session, and it happens to be while the framework is handling a `JWTAuthenticationSuccessResponse` from this bundle.

On the Request/Response page of the web profiler, there should be a Session tab showing all the session uses.  You should be able to use that to find what's starting the session here.  Or, a good ol' fashioned `debug_backtrace(\DEBUG_BACKTRACE_IGNORE_ARGS)` in the `onSessionUsage()` method in `vendor/symfony/http-kernel/EventListener/AbstractSessionListener.php` if the data collector isn't recording it for whatever reason.

**Comment by ChristianVermeulen** [comment]
Thanks for that, I checked the sessions in the profiler and indeed we add a session ourselves. However, this has been the case since we started building our app 😓. It is something we can't go without either, so I had to set `stateless: false` in the firewall config.

I wonder if SF6.2 was not as strict about stateless requests and sessions since it was no problem before I upgraded to SF6.3.

**Comment by mbabker** [comment]
Something did change as I stumbled on https://github.com/symfony/symfony/issues/50310 testing the betas, but can't say I know what exactly changed.

**Comment by derWebdesigner** [comment]
Short hint: I checked everything and already thought this is a bug since Symfony 6.3 until I discovered after hours of searching that I had an EventSubscriber which used the Session. Maybe this helps somebody to save these hours... :-)

**Comment by antoinemineau** [comment]
Same issue here, I reverted back to sf 6.2.
Didn't find what caused this issue

**Comment by derWebdesigner** [comment]
@antoinemineau If I understood it correctly, reverting it will not solve the actual issue because you are using the session already although you marked a route as stateless. It's just that S6.3 throws an error where it didn't do that before.

**Comment by antoinemineau** [comment]
By reverting to sf 6.2, the exception is not thrown which doesn't break the app.
When I have more time I will try to debug the cause, probably an event using a session like you said.
Will give feedback here if I find the culprit.

**Comment by Ciloe** [comment]
Same issue here

**Comment by Seb33300** [comment]
Hi guys, I created a PR on symfony that may fix that issue.
Can you please try it and confirm if that works for you?
https://github.com/symfony/symfony/pull/51350

**Comment by ICS-Vortex** [comment]
Any news on this?

**Comment by Seb33300** [comment]
The fix has been merged in Symfony 6.3 and already available in the latest release.
If you updated your project to the latest Symfony version and you still have that bug, this means the issue is in your project.
You need to find where your are accessing session in your project (can be in a Listener, a Service, ...)

**Comment by sandeep-parekh-sublimis** [comment]
wanted to share an important detail about Symfony routing that can be quite useful in certain scenarios In Symfony when defining routes using annotations, you have the option to set stateless: false in a route annotation.

#[Route('/', name: 'homepage', stateless: false)]

**Comment by ICS-Vortex** [comment]
> wanted to share an important detail about Symfony routing that can be quite useful in certain scenarios In Symfony when defining routes using annotations, you have the option to set stateless: false in a route annotation.
> 
> #[Route('/', name: 'homepage', stateless: false)]

Disagree. API should be stateless. 
BTW, fixed my issue. Really, session was used in some of my subscribers during requesting routes under API firewall.

**Comment by constantinosergiou** [comment]
> > wanted to share an important detail about Symfony routing that can be quite useful in certain scenarios In Symfony when defining routes using annotations, you have the option to set stateless: false in a route annotation.
> > #[Route('/', name: 'homepage', stateless: false)]
> 
> Disagree. API should be stateless. BTW, fixed my issue. Really, session was used in some of my subscribers during requesting routes under API firewall.

could please tell me what you change to fix it? i have the same issue and do not want to put stateless: false

**Comment by Seb33300** [comment]
> could please tell me what you change to fix it? i have the same issue and do not want to put stateless: false

@constantinosergiou You need to search in your project any code using `$request->getSession()` and get rid of it.

**Comment by ICS-Vortex** [comment]
> > > wanted to share an important detail about Symfony routing that can be quite useful in certain scenarios In Symfony when defining routes using annotations, you have the option to set stateless: false in a route annotation.
> > > #[Route('/', name: 'homepage', stateless: false)]
> > 
> > 
> > Disagree. API should be stateless. BTW, fixed my issue. Really, session was used in some of my subscribers during requesting routes under API firewall.
> 
> could please tell me what you change to fix it? i have the same issue and do not want to put stateless: false

Yeah, as Seb already answered,  you need to find any usages of the session.  
In my case, I had a LocaleListener which was using a session in onKernelRequest method, so, I just checked what host I am requesting now, and if it's API host - I return void. So, basically,  session is  not used anymore during api request.

**Comment by Seb33300** [comment]
> Yeah, as Seb already answered, you need to find any usages of the session. In my case, I had a LocaleListener which was using a session in onKernelRequest method, so, I just checked what host I am requesting now, and if it's API host - I return void. So, basically, session is not used anymore during api request.

You should check if the current request is stateless or not using `$request->attributes->getBoolean('_stateless')` instead of checking the host.

**Comment by ICS-Vortex** [comment]
> > Yeah, as Seb already answered, you need to find any usages of the session. In my case, I had a LocaleListener which was using a session in onKernelRequest method, so, I just checked what host I am requesting now, and if it's API host - I return void. So, basically, session is not used anymore during api request.
> 
> You should check if the current request is stateless or not using `$request->attributes->getBoolean('_stateless')` instead of checking the host.

Thx, but I am happy enough with my solution.
Everything is ok and right, until you start acting with session. 
Your solution suppose to edit every route I have in the project.
My way - I edit code only at one single line.

**Comment by jwandrews** [comment]
Just ran into this. Dropping this comment here just in case it's relevant to someone in the future.

While doing bit of digging in the Symfony Profiler, I noticed that `FormLoginAuthenticator` accesses the session. Therefore, if using `form_login` in `security.yaml` with `stateless: true` set, this could be causing the exception

**Comment by Seb33300** [comment]
@jwandrews What version of Symfony do you use?
This bug has been fixed in Symfony 6.3

**Comment by andersonpem** [comment]
If any of you guys are still having this, add stateless: false to routes.yaml
Example:
```yaml
api:
  resource: '../src/Controller/'
  type: annotation
  defaults: { guard_protected: true }
  # Add this:
  stateless: false
```

**Comment by demcy** [comment]
on symfony 7.0 how to fix?

**Comment by ICS-Vortex** [comment]
> on symfony 7.0 how to fix?

Make sure u aren't using Session during api request.
Check all your listeners, subscribers,  etc...

**Comment by jamesgathu** [comment]
Note that if you are on API platform 3.0 there is a configuration for stateless
```yaml
api_platform:
  ...
  defaults:
    stateless: true
```
If your API needs the state, then proceed to switch this to `false`

**Comment by jwandrews** [comment]
@Seb33300 IIRC, I was upgrading to a version < 6.3 at the time.

more recently have upgraded to 6.4.* and everything is running fine again

**Comment by PaulCombal** [comment]
I had the issue, it was completely unrelated.

Somewhere in a repo I had:

`->andWhere('o.prop = "a string"')`

I fixed it using a named parameter:

`->andWhere('o.prop = :strParam')`

It happened another time because I did:

`->orderBy('o.id DESC')`

Instead of

`->orderBy('o.id', 'DESC')`

So I guess check your query builders if this happens to you. Symfony 6.4.
