### ISSUE TITLE
Issued at is in the Future

### ISSUE THREAD

**Issue by tiagobrito** [lexik/LexikJWTAuthenticationBundle#286]
I have the token encode & decode in different machines. it seems that the then JWT Authentication is doing the decode of the token it fails due to the `iat` parameter > time().
What I'm doing wrong ?

**Comment by chalasr** [comment]
Hi @tiagobrito, that's strange. It looks like the server from which you're decoding the token doesn't have the same clock as the one that created it (your decoding server time being apparently lower than the one of your encoding server).

Could you please visit http://currenttimestamp.com/ from these two machines, or do a `php -r "echo time();"`? So we can see the importance of the difference. 

From the jwt spec:

> Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew.

Depending on the result, I think we would have to either add support for `clock_skew` or allow to disable the iat claim verification.

For reference:
https://docs.oracle.com/cd/E55956_01/doc.11123/oauth_guide/content/oauth_access_token_jwt.html
https://github.com/mozilla/addons-server/issues/1461
http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html

**Comment by tiagobrito** [comment]
@chalasr Thanks for your reply.
Do you know if there is a way to disable the iat claim verification ?

**Comment by Spomky** [comment]
If you have a time discrepancy between the server and a client, `iat` should not be the only claim that is affected. You will have troubles with the `nbf` one and, more important, with the `exp` one.

I had experiences with such an issue. The problem was not about the timestamp of each stakeholder, but the fact that the client used a timestamp with the timezone and not the current Unix timestamp (i.e. at the UTC time zone).

**Comment by tiagobrito** [comment]
@Spomky We are using the unix timestamp in both (server and clients). And after some debug, I checked that we got an invalid token due to the `$this->checkIssuedAt();` on `LoadedJWS` class.

**Comment by jpillias** [comment]
I think we have the same problem here. Did you found any solution ?

**Comment by chalasr** [comment]
@jpillias Since we did not identified the problem and it's apparently not something wrong in the code base which is tested on CI platforms, we didn't investigated yet.
Thanks for telling us that you runs into the same issue, it can definitely only help and its much appreciated.

I'll try to look deeper at what is possible to do, keep you informed in the next days.

**Comment by chalasr** [comment]
I'm closing this issue as won't fix for now. Please let us know if you find how to fix the issue or if you face the same.

**Comment by jpillias** [comment]
Just for information, the problem was on our server.

We had load balancing with 2 front server. Servers were not date sync (ntpd), so they had more than 10s difference between both.
=> If you log on the server wich is "in the futur", it give's you a token with a futur timestamp, wich give an error during 10s on the other server.

**Comment by chalasr** [comment]
@jpillias Thank you for sharing!

**Comment by patrickjDE** [comment]
So there is currently no way to account for clock skew?

**Comment by chalasr** [comment]
Fixed by #492

**Comment by mu4ddi3** [comment]
Well i use newest - 2.5.4 version of this bundle in my project and problem still exist, even with fix #492.

Problem start in "load" method of LcobucciJWSProvider.php.
This method return new LoadedJWS object, which have "$this->verify($jws)" in constructor. This cause the problems. "verify" method return false when try to do $jwt->validate  ($jwt is Lcobucci\JWT\Token). One of validation it makes is checking "nbf" but it does not take into account the clockSkew parameter.

**Comment by chalasr** [comment]
@mu4ddi3 The `clock_skew` option is a feature that has been released in v2.5.0, so you should be able to set the `lexik_jwt_authentication.clock_skew` option according to your need if you are using v2.5.4. Please open a new issue if you still think there is something wrong, comments on closed issues/PRs are likely to be lost. Thanks

**Comment by mu4ddi3** [comment]
done [https://github.com/lexik/LexikJWTAuthenticationBundle/issues/573](url)
